### ISSUE TITLE
Mark as [DONE] 0.7.0 Release + Epic

### ISSUE THREAD

**Issue by MaxLynam** [for-good/isgood-webapp#11]
Woohoo  🎉

We got it all setup up with our working code base to continue developing from.

🏆  BIG achievement and hurdle overcome, enabling us to now move nice and fast on feature deliverables 

Test:
- [x] other tasks done 
- [x] verified each bit works in our code
- [x] verified works on the host/sever (amazee)
- [x] ~~are we able to sync release verions 0.7.0 in github and zenhub?~~

Then:
- [ ] Mark this epic as complete
- [ ] Is epic shown as complete?
- [ ] Can we see a deploy ~~and version~~ in github and zenhub?
- [ ] Are the tasks, etc all marked as complete as well?

**Comment by MaxLynam** [comment]
before sign off of all of this, I am going to go through this checklist, and also ensure all is working the same for the comms website, using the webapp code base as the basis for a proper workig codebase with secure and collaborative workflows for dev/build AND devops. --- WOOHOO !!!!

**Comment by MaxLynam** [comment]
ignoring requirement to have a release on completing this epic ... but, we have it working and deployed !!!

First thing on next epic is to bring in the EKAN code to our repo, then check all the syncs again.
